# Generated by Django 4.0.10 on 2023-03-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='investments',
            field=models.ManyToManyField(to='core.investment'),
        ),
    ]
