# Generated by Django 4.0.10 on 2023-03-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='core.ingredient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='investments',
            field=models.ManyToManyField(to='core.project'),
        ),
    ]
