# Generated by Django 4.1.1 on 2022-10-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_detail_extra_price_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='investments',
            field=models.ManyToManyField(to='core.project'),
        ),
    ]
