# Generated by Django 4.0.10 on 2023-03-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_recipe_ingredients_alter_user_investments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invest',
            field=models.ManyToManyField(to='core.investment'),
        ),
    ]
