# Generated by Django 4.0.10 on 2023-03-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_invest'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
