# Generated by Django 4.0.10 on 2023-04-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_investment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commission',
            new_name='Bonus',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='commission',
            new_name='bonus',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='commission',
            new_name='bonus',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='commission',
            new_name='bonus',
        ),
    ]
