# Generated by Django 4.0.10 on 2023-04-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_referral_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='staff',
        ),
    ]
