# Generated by Django 4.0.10 on 2023-04-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_referral_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
