# Generated by Django 4.0.10 on 2023-06-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_project_bath_rooms_project_bed_rooms_project_garage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bath_rooms',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bed_rooms',
        ),
        migrations.AddField(
            model_name='project',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
    ]
