# Generated by Django 4.0.10 on 2023-06-18 02:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_project_bath_rooms_remove_project_bed_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=50)),
                ('etag', models.CharField(max_length=60)),
                ('id_kind', models.CharField(max_length=20)),
                ('id_video_id', models.CharField(max_length=30, unique=True)),
                ('snippet_published_at', models.CharField(max_length=30)),
                ('snippet_channel_id', models.CharField(max_length=40)),
                ('snippet_title', models.CharField(max_length=255)),
                ('snippet_description', models.CharField(max_length=255)),
                ('snippet_thumbnails_default_url', models.CharField(max_length=255)),
                ('snippet_thumbnails_default_width', models.IntegerField()),
                ('snippet_thumbnails_default_height', models.IntegerField()),
                ('snippet_thumbnails_medium_url', models.CharField(max_length=255)),
                ('snippet_thumbnails_medium_width', models.IntegerField()),
                ('snippet_thumbnails_medium_height', models.IntegerField()),
                ('snippet_thumbnails_high_url', models.CharField(max_length=255)),
                ('snippet_thumbnails_high_width', models.IntegerField()),
                ('snippet_thumbnails_high_height', models.IntegerField()),
                ('snippet_channel_title', models.CharField(max_length=255)),
                ('snippet_live_broadcast_content', models.CharField(max_length=255)),
                ('snippet_publish_time', models.CharField(max_length=30)),
            ],
        ),
    ]
