# Generated by Django 4.0.10 on 2023-07-02 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
