# Generated by Django 4.0.10 on 2023-07-03 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_investment_ordinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
