---
name: Checks

on: [push]

jobs:
  test-lint: #id of the job
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 #Allow us to use actions in github repository
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python3 manage.py test" #Arranca los test en github
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"